pets/config/routes.rb
Pets::Application.routes.draw do
  resources :adoption_agreements

  get "store/index"
  resources :pets

  root 'store#index', as: 'store'

  

end

pets/app/models/adoption_agreement.rb
class AdoptionAgreement < ActiveRecord::Base
  has_one :pet, dependent: :destroy
end

pets/app/models/pet.rb
class Pet < ActiveRecord::Base
  
  belongs_to :adoption_agreements
  
  validates :name, :description, :breed, :image_url, presence: true;
  validates :age, numericality: {greater_than_or_equal_to: 0}
  validates :image_url, allow_blank: true, :format => { :with => %r{\.(gif|jpg|png)\Z}i, :message => 'must be a URL for GIF, JPG or PNG image.'}
end

pets/app/controllers/adoption_agreements_controller.rb
class AdoptionAgreementsController < ApplicationController
  before_action :set_adoption_agreement, only: [:show, :edit, :update, :destroy]

  # GET /adoption_agreements
  # GET /adoption_agreements.json
  def index
    @adoption_agreements = AdoptionAgreement.all
  end

  # GET /adoption_agreements/1
  # GET /adoption_agreements/1.json
  def show
  end

  # GET /adoption_agreements/new
  def new
    @adoption_agreement = AdoptionAgreement.new
  end

  # GET /adoption_agreements/1/edit
  def edit
  end

  # POST /adoption_agreements
  # POST /adoption_agreements.json
  def create
    @pet = Pet.find(params[:pet_id])
    @adoption_agreement = AdoptionAgreement.new(adoption_agreement_params)

    respond_to do |format|
      if @adoption_agreement.save
        format.html { redirect_to @adoption_agreement, notice: 'Adoption agreement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @adoption_agreement }
      else
        format.html { render action: 'new' }
        format.json { render json: @adoption_agreement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adoption_agreements/1
  # PATCH/PUT /adoption_agreements/1.json
  def update
    respond_to do |format|
      if @adoption_agreement.update(adoption_agreement_params)
        format.html { redirect_to @adoption_agreement, notice: 'Adoption agreement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @adoption_agreement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adoption_agreements/1
  # DELETE /adoption_agreements/1.json
  def destroy
    @adoption_agreement.destroy
    respond_to do |format|
      format.html { redirect_to adoption_agreements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adoption_agreement
      @adoption_agreement = AdoptionAgreement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adoption_agreement_params
      params[:adoption_agreement]
    end
end

pets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

pets/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :description, :breed, :age, :image_url)
    end
end

pets/app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @pets = Pet.order(:name);
  end
end

pets/app/helpers/adoption_agreements_helper.rb
module AdoptionAgreementsHelper
end

pets/app/helpers/application_helper.rb
module ApplicationHelper
end

pets/app/helpers/pets_helper.rb
module PetsHelper
end

pets/app/helpers/store_helper.rb
module StoreHelper
end

pets/app/views/adoption_agreements/_form.html.erb
<%= form_for(@adoption_agreement) do |f| %>
  <% if @adoption_agreement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adoption_agreement.errors.count, "error") %> prohibited this adoption_agreement from being saved:</h2>

      <ul>
      <% @adoption_agreement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pets/app/views/adoption_agreements/edit.html.erb
<h1>Editing adoption_agreement</h1>

<%= render 'form' %>

<%= link_to 'Show', @adoption_agreement %> |
<%= link_to 'Back', adoption_agreements_path %>

pets/app/views/adoption_agreements/index.html.erb
<h1>Listing adoption_agreements</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @adoption_agreements.each do |adoption_agreement| %>
      <tr>
        <td><%= link_to 'Show', adoption_agreement %></td>
        <td><%= link_to 'Edit', edit_adoption_agreement_path(adoption_agreement) %></td>
        <td><%= link_to 'Destroy', adoption_agreement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adoption agreement', new_adoption_agreement_path %>

pets/app/views/adoption_agreements/new.html.erb
<h1>New adoption_agreement</h1>

<%= render 'form' %>

<%= link_to 'Back', adoption_agreements_path %>

pets/app/views/adoption_agreements/show.html.erb
<p id="notice"><%= notice %></p>

<%= @pet.name %>

pets/app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pets/app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

pets/app/views/pets/index.html.erb
<h1>Listing Pets</h1>


<table>
<% @pets.each do |pet| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    
    <td>
      <%= image_tag(pet.image_url, :class => 'list_image') %>
    </td>
    
    <td class="list_description">
      <dl>
        <dt><%= pet.name %></dt>
        <dd><%= truncate(strip_tags(pet.description), :length => 80) %></dd>
        <dd>Breed: <%= pet.breed %></dd>
      </dl>
    </td>
    
    <td class="list_actions">
      <%= link_to 'Show' , pet %><br/>
      <%= link_to 'Edit' , edit_pet_path(pet) %><br/>
      <%= link_to 'Destroy' , pet, :confirm => 'Are you sure?' , :method => :delete %>
      
    
    </td>
  </tr>
  <% end %>
</table>


<br />

<%= link_to 'New Pet', new_pet_path %>

pets/app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

pets/app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet.description %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @pet.image_url %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

pets/app/views/store/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Your Foster Animal Catalog</h1>

<% @pets.each do |pet| %>
  <div class="entry">
    <%= image_tag(pet.image_url) %>
    <h3><%= pet.name %></h3>
    <h4><%= pet.breed %></h4>
    <h4><%= pet.age %> year<% if pet.age > 1 %>s<% end %> old.</h4>
    <%= sanitize(pet.description) %>
    <%= button_to 'Adopt Pet', adoption_agreements_path(pet_id: pet); %>

  </div>
<% end %>